<a href="https://colab.research.google.com/github/mbz135/Analisis_de_datos/blob/main/Analisis_version1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#TRABAJO CPS

IMPORTACION DE LIBRERIAS

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import hashlib

In [5]:
dd=pd.read_csv("/Datos.csv")

In [6]:
dd.head(30)

    Unnamed: 0 id_paciente edad heart_rate   spo2 respiratory_rate
0            0           1   19       76.0   99.0             17.0
1            1           2   67       79.0   99.0             18.0
2            2           3   61       96.0    NaN             17.0
3            3           4   21       89.0   97.0             15.0
4            4           5   84       70.0  146.0             15.0
5            5           6   34       45.0   99.0             18.0
6            6           7   36      102.0   96.0             13.0
7            7           8   31       87.0   97.0             17.0
8            8           9   42       80.0  100.0             19.0
9            9          10   30       71.0   98.0             17.0
10          10          11   43       97.0   98.0             17.0
11          11          12   77       57.0   98.0             17.0
12          12          13   50       69.0   97.0             17.0
13          13          14   85       60.0   96.0             16.0
14          14          15   50       82.0   98.0             12.0
15          15          16   38       72.0   96.0             11.0
16          16          17   75      103.0  100.0             17.0
17          17          18   77       78.0   96.0             15.0
18          18          19   80       20.0   97.0             21.0
19          19          20   82       31.0   98.0              NaN
20          20          21   19       69.0   97.0             21.0
21          21          22   55       65.0   98.0             14.0
22          22          23   37       84.0   98.0             20.0
23          23          24   35       72.0   99.0             17.0
24          24          25   35       58.0   98.0             19.0
25          25          26   78       53.0   98.0             14.0
26          26          27   75       79.0   98.0             14.0
27          27          28   33       79.0   98.0             15.0
28          28          29   47       77.0   97.0             20.0
29          29          30   72       83.0   98.0             17.0

In [7]:
dd.shape
dd.columns
dd.dtypes

Unnamed: 0           int64
id_paciente         object
edad                object
heart_rate          object
spo2                object
respiratory_rate    object
dtype: object

In [8]:
dd.isnull().sum()

Unnamed: 0           0
id_paciente          0
edad                10
heart_rate          23
spo2                18
respiratory_rate    12
dtype: int64

In [9]:
filas_con_nulos=dd.isnull().any(axis=1).sum()

print(filas_con_nulos )

62

In [10]:
dd==""

     Unnamed: 0  id_paciente   edad  heart_rate   spo2  respiratory_rate
0         False        False  False       False  False             False
1         False        False  False       False  False             False
2         False        False  False       False  False             False
3         False        False  False       False  False             False
4         False        False  False       False  False             False
..          ...          ...    ...         ...    ...               ...
520       False        False  False       False  False             False
521       False        False  False       False  False             False
522       False        False  False       False  False             False
523       False        False  False       False  False             False
524       False        False  False       False  False             False

[525 rows x 6 columns]

In [11]:
dd.apply(lambda col: col.astype(str).str.strip()=="")

     Unnamed: 0  id_paciente   edad  heart_rate   spo2  respiratory_rate
0         False        False  False       False  False             False
1         False        False  False       False  False             False
2         False        False  False       False  False             False
3         False        False  False       False  False             False
4         False        False  False       False  False             False
..          ...          ...    ...         ...    ...               ...
520       False        False  False       False  False             False
521       False         True  False       False  False             False
522       False        False  False       False  False             False
523       False        False  False       False  False             False
524       False        False  False       False  False             False

[525 rows x 6 columns]

In [12]:

columnas_signos = ['heart_rate', 'spo2', 'respiratory_rate']


dd[columnas_signos] = dd[columnas_signos].apply(pd.to_numeric, errors='coerce')


estadisticas = dd[columnas_signos].describe()

print("--- Estadísticas de Signos Vitales ---")
print(estadisticas)

--- Estadísticas de Signos Vitales ---
       heart_rate        spo2  respiratory_rate
count  488.000000  498.000000        510.000000
mean    77.854508   97.423695         16.213725
std     16.456693    5.378173          4.506643
min     20.000000   57.000000          3.000000
25%     69.000000   97.000000         14.000000
50%     78.000000   98.000000         16.000000
75%     88.000000   98.000000         18.000000
max    148.000000  146.000000         65.000000

Se busco un registro de personas mayores a 60 años que tengan una frecuencia 100

In [13]:
dd['edad'] = pd.to_numeric(dd['edad'], errors='coerce')


dd['heart_rate'] = pd.to_numeric(dd['heart_rate'], errors='coerce')



condicion_edad= dd['edad']>60
condicion_frecuencia = dd['heart_rate'] > 100


registros_criticos = dd[condicion_edad & condicion_frecuencia]


print(f"Se encontraron {len(registros_criticos)} registros que cumplen ambas condiciones.")
display(registros_criticos)

Se encontraron 12 registros que cumplen ambas condiciones.

     Unnamed: 0 id_paciente  edad  heart_rate   spo2  respiratory_rate
16           16          17  75.0       103.0  100.0              17.0
94           94          95  70.0       101.0   99.0              18.0
115         115         116  63.0       109.0   96.0               8.0
214         214         215  86.0       103.0   96.0              14.0
237         237         238  72.0       104.0   97.0              13.0
269         269         270  87.0       145.0   99.0               NaN
335         335         336  73.0       140.0   99.0              18.0
354         354         355  86.0       148.0   98.0              20.0
357         357         358  62.0       101.0   95.0              19.0
368         368         369  75.0       107.0   97.0               3.0
467         467         468  68.0       129.0   97.0              17.0
469         469         470  63.0       105.0   98.0              17.0

In [14]:
dd['edad'] = pd.to_numeric(dd['edad'], errors='coerce')


dd['heart_rate'] = pd.to_numeric(dd['heart_rate'], errors='coerce')



condicion_edad= dd['edad']<30
condicion_frecuencia = dd['heart_rate'] > 100


registros_criticos = dd[condicion_edad & condicion_frecuencia]


print(f"Se encontraron {len(registros_criticos)} registros que cumplen ambas condiciones.")
display(registros_criticos)

Se encontraron 2 registros que cumplen ambas condiciones.

     Unnamed: 0 id_paciente  edad  heart_rate   spo2  respiratory_rate
304         304         305  21.0       132.0  100.0              15.0
452         452         453  26.0       107.0   97.0              14.0

In [15]:
dd['edad'] = pd.to_numeric(dd['edad'], errors='coerce')


dd['heart_rate'] = pd.to_numeric(dd['heart_rate'], errors='coerce')



condicion_edad= dd['edad']<20
condicion_frecuencia = dd['heart_rate'] > 100


registros_criticos = dd[condicion_edad & condicion_frecuencia]


print(f"Se encontraron {len(registros_criticos)} registros que cumplen ambas condiciones.")
display(registros_criticos)

Se encontraron 0 registros que cumplen ambas condiciones.

Empty DataFrame
Columns: [Unnamed: 0, id_paciente, edad, heart_rate, spo2, respiratory_rate]
Index: []

In [16]:
columnas_validar = ['heart_rate', 'respiratory_rate', 'spo2']
dd[columnas_validar] = dd[columnas_validar].apply(pd.to_numeric, errors='coerce')

#Creamos las validaciones (True si es normal, False si es inválido/nulo)
# Frecuencia cardiaca: 60 - 100
dd['fc_valida'] = dd['heart_rate'].between(60, 100)

# Frecuencia respiratoria: 12 - 20
dd['fr_valida'] = dd['respiratory_rate'].between(12, 20)

# Saturación de oxígeno: 95 - 100
dd['spo2_valida'] = dd['spo2'].between(95, 100)

# 3. Contar cuántos datos inválidos hay por cada signo
print("Conteo de registros VÁLIDOS por categoría:")
print(dd[['fc_valida', 'fr_valida', 'spo2_valida']].sum())

Conteo de registros VÁLIDOS por categoría:
fc_valida      413
fr_valida      451
spo2_valida    479
dtype: int64

In [17]:
dd_limpio = dd[dd['fc_valida'] & dd['fr_valida'] & dd['spo2_valida']]

print(f"Registros totales originales: {len(dd)}")
print(f"Registros con datos fisiológicamente válidos: {len(dd_limpio)}")

Registros totales originales: 525
Registros con datos fisiológicamente válidos: 333

In [18]:
dd = dd.replace(r'^\s*$', np.nan, regex=True)

In [19]:
dd = dd.drop_duplicates()

In [21]:
filas_con_nulos = dd.isnull().any(axis=1).sum()
print(filas_con_nulos)

91

In [23]:
filas_con_nulos_inicial = dd.isnull().any(axis=1).sum()

In [24]:
print("Antes:", filas_con_nulos_inicial)
print("Después:", filas_con_nulos)
print("Diferencia:", filas_con_nulos - filas_con_nulos_inicial)

Antes: 91
Después: 91
Diferencia: 0